### ISSUE TITLE
Web APIs 实践，最后更新2024/02月...

### ISSUE THREAD

**Issue by taoliujun** [taoliujun/blog#49]
[Web API](https://developer.mozilla.org/en-US/docs/Web/API)的发展日新月异，稍不留神就偷偷的出了新规范，这些规范为项目方案提供更多的可能性。话说读百遍不如写一遍，计划在一段时间内，对大部分API进行demo实践以加深印象。

**Comment by taoliujun** [comment]
### A

- [ ] [Audio Output Devices API](https://developer.mozilla.org/en-US/docs/Web/API/Audio_Output_Devices_API) 选择音频播放设备。*Experimental*

**Comment by taoliujun** [comment]
### B

- [ ] [Background Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Fetch_API) 在后台下载大文件。*Experimental*
- [ ] [Background Sync](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API) 延迟任务以便在网络稳定时运行。*Experimental*
- [x] #55，[Background Tasks](https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API) 利用空闲时间跑阻塞的任务。
- [x] #50，[Badging API](https://developer.mozilla.org/en-US/docs/Web/API/Badging_API) 在web App中设置图标徽章。
- [ ] [Barcode Detection API](https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API)，读取图片流中的条码、二维码。*Experimental*
- [x] #58，[Battery API](https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API) 获取设备电池状态。
- [x] #53，[Beacon](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) 发送无需响应的请求，保证浏览器关闭之前发送完毕。
- [ ] [Bluetooth API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API) 连接蓝牙。*Experimental*
- [x] #59，[Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) 跨标签、窗口通信。

**Comment by taoliujun** [comment]
### A

- [ ] [Audio Output Devices API](https://developer.mozilla.org/en-US/docs/Web/API/Audio_Output_Devices_API) 选择音频播放设备。*Experimental*

### B

- [ ] [Background Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Fetch_API) 在后台下载大文件。*Experimental*
- [ ] [Background Sync](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API) 延迟任务以便在网络稳定时运行。*Experimental*
- [x] #55，[Background Tasks](https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API) 利用空闲时间跑阻塞的任务。
- [x] #50，[Badging API](https://developer.mozilla.org/en-US/docs/Web/API/Badging_API) 在web App中设置图标徽章。
- [ ] [Barcode Detection API](https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API)，读取图片流中的条码、二维码。*Experimental*
- [x] #58，[Battery API](https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API) 获取设备电池状态。
- [x] #53，[Beacon](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) 发送无需响应的请求，保证浏览器关闭之前发送完毕。
- [ ] [Bluetooth API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API) 连接蓝牙。*Experimental*
- [x] #59，[Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) 跨标签、窗口通信。

### C

- [ ] [CSS Counter Styles](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Counter_Styles) 为CSS定义计数器。
- [x] #63，[CSS Custom Highlight API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Custom_Highlight_API) 设置元素的高亮区域。
- [x] #65，[CSS Font Loading API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API) 字体加载管理。
- [ ] [CSS Painting API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API) 为CSS的背景等属性提供自定义的图片绘制。*Experimental*
- [x] #67，[CSS Properties and Values API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Properties_and_Values_API) 为CSS扩展属性，类似`CSS variables`。
- [x] #69，[CSS Typed Object Model API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Typed_OM_API) 提供了一系列访问和操作CSS值的方法。
- [x] #71，[CSSOM](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model) 管理CSS的方法合集，类似DOM。
- [ ] [Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) 画图。  
- [ ] [Channel Messaging API](https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API) 又一种跨窗口通信。
- [x] #72，[Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) 访问、写入系统剪切板。
- [ ] [Compression Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API) 使用`gzip`、`deflate`压缩数据流。 
- [ ] [Console API](https://developer.mozilla.org/en-US/docs/Web/API/Console_API) 控制台日志输出。
- [ ] [Contact Picker API](https://developer.mozilla.org/en-US/docs/Web/API/Contact_Picker_API) 选择设备上的联系人。*Experimental*
- [ ] [Content Index API](https://developer.mozilla.org/en-US/docs/Web/API/Content_Index_API) 设置`service worker`的离线数据。*Experimental*
- [x] #75，[Cookie Store API](https://developer.mozilla.org/en-US/docs/Web/API/Cookie_Store_API) 优雅的管理cookie。
- [x] #77，[Credential Management API](https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API) 管理登录凭证。

### D

- [x] #80，[DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) 元素操作的方法合集。
- [x] #79，[Device Memory API](https://developer.mozilla.org/en-US/docs/Web/API/Device_Memory_API) 访问设备可用内存大小。
- [x] #81，[Device Orientation Events](https://developer.mozilla.org/en-US/docs/Web/API/Device_orientation_events) 访问设备的物理方向。
- [x] #82，[Document Picture-in-Picture API](https://developer.mozilla.org/en-US/docs/Web/API/Document_Picture-in-Picture_API) 画中画。*experimental*

### E

- [ ] [EditContext API](https://developer.mozilla.org/en-US/docs/Web/API/EditContext_API) 富文本交互 *Experimental*
- [ ] [Encoding API](https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API) 字符编码解码
- [ ] [Encrypted Media Extensions](https://developer.mozilla.org/en-US/docs/Web/API/Encrypted_Media_Extensions_API) 支持数字版权内容
- [x] #84，[EyeDropper API](https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper_API) 颜色吸管 *Experimental*

### F

- [ ] [FedCM API](https://developer.mozilla.org/en-US/docs/Web/API/FedCM_API) *Experimental*
- [ ] [Fenced Frame API](https://developer.mozilla.org/en-US/docs/Web/API/Fenced_frame_API) *Experimental*
- [ ] [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) 发起网络请求，代替XMLHttpRequest
- [x] #85，[File API](https://developer.mozilla.org/en-US/docs/Web/API/File_API) 访问用户选择的文件
- [x] #86，[File System API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API) 访问、写入操作系统上的文件
- [ ] [File and Directory Entries API](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API) 虚拟文件系统
- [ ] [Force Touch Events](https://developer.mozilla.org/en-US/docs/Web/API/Force_Touch_events) Non-standard
- [x] #87，[Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) 元素全屏

### G

- [ ] [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API) 访问手柄设备
- [x] #88，[Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)  访问地理位置
- [ ] [Geometry Interfaces](https://developer.mozilla.org/en-US/docs/Web/API/Geometry_interfaces) 几何形状

**Comment by taoliujun** [comment]
### H
- [ ] [HTML DOM](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API) DOM操作，包括form data、canvas、video等
- [ ] [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) 拖放
- [ ] [HTML Sanitizer API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API) 安全的HTML字符串 *Experimental*
- [ ] [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) 浏览器会话记录
- [ ] [Houdini API](https://developer.mozilla.org/en-US/docs/Web/API/Houdini_APIs) 扩展CSS的样式和布局

### I
- [ ] [Idle Detection API](https://developer.mozilla.org/en-US/docs/Web/API/Idle_Detection_API) *Experimental*
- [ ] [Image Capture API](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Image_Capture_API) 拍照，调用设备捕获图像 *Experimental*
- [ ] [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) 客户端数据库
- [ ] [Ink API](https://developer.mozilla.org/en-US/docs/Web/API/Ink_API) 调用系统的笔触合成功能 *Experimental*
- [ ] [Input Device Capabilities API](https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceCapabilities_API) *Experimental*
- [ ] [Insertable Streams for MediaStreamTrack API](https://developer.mozilla.org/en-US/docs/Web/API/Insertable_Streams_for_MediaStreamTrack_API) 操作媒体流，比如合成音频、往视频里加一个帽子
- [ ] [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) 监听元素是否出现在视口

### K
- [ ] [Keyboard API](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard_API) 访问物理键盘的信息、如布局等 *Experimental*

### L
- [ ] [Launch Handler API](https://developer.mozilla.org/en-US/docs/Web/API/Launch_Handler_API) 获取PWA的启动方式 *Experimental*
- [ ] [Local Font Access API](https://developer.mozilla.org/en-US/docs/Web/API/Local_Font_Access_API) 访问用户本地安装的字体列表 *Experimental*

### M
- [ ] [Media Capabilities API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Capabilities_API) 获取设备的解码、编码能力，以及实时反馈
- [ ] [Media Capture and Streams](https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API) 媒体捕捉和媒体流
- [ ] [Media Session API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API) 获取设备对媒体的控制
- [ ] [Media Source Extensions](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API) 创建媒体流 *Experimental*
- [ ] [MediaStream Recording](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API) 录制媒体流

### N
- [ ] [Navigation API](https://developer.mozilla.org/en-US/docs/Web/API/Navigation_API) 对`History`和`Location`的扩展，可以拦截管理浏览器导航 *Experimental*
- [ ] [Network Information API](https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API) 访问网络连接信息 *Experimental*

**Comment by taoliujun** [comment]
### O

//

### P
- [x] #95， [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) 访问页面可见性
- [ ] [Payment Handler API](https://developer.mozilla.org/en-US/docs/Web/API/Payment_Handler_API) *Experimental*
- [ ] [Payment Request API](https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API)
- [ ] [Performance API](https://developer.mozilla.org/en-US/docs/Web/API/Performance_API)
- [ ] [Periodic Background Sync](https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API) *Experimental*
- [ ] [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API)
- [ ] [Picture-in-Picture API](https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API)
- [ ] [Pointer Events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events)
- [ ] [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API)
- [ ] [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API)
- [ ] [Presentation API](https://developer.mozilla.org/en-US/docs/Web/API/Presentation_API) *Experimental*
- [ ] [Prioritized Task Scheduling API](https://developer.mozilla.org/en-US/docs/Web/API/Prioritized_Task_Scheduling_API)
- [ ] [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API)

### Q

//

### R
- [ ] [Remote Playback API](https://developer.mozilla.org/en-US/docs/Web/API/Remote_Playback_API)
- [ ] [Reporting API](https://developer.mozilla.org/en-US/docs/Web/API/Reporting_API) *Experimental*
- [ ] [Resize Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Resize_Observer_API)

### S
- [ ] [SVG](https://developer.mozilla.org/en-US/docs/Web/API/SVG_API)
- [ ] [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API)
- [ ] [Screen Orientation API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Orientation_API)
- [ ] [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API)
- [ ] [Selection API](https://developer.mozilla.org/en-US/docs/Web/API/Selection_API)
- [ ] [Sensor API](https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs)
- [ ] [Server Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events)
- [ ] [Service Workers API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)
- [ ] [Shared Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Shared_Storage_API) *Experimental*
- [ ] [Speculation Rules API](https://developer.mozilla.org/en-US/docs/Web/API/Speculation_Rules_API) *Experimental*
- [ ] [Storage](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API)
- [ ] [Storage Access API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API)
- [ ] [Streams](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API)

### T
- [ ] [Topics API](https://developer.mozilla.org/en-US/docs/Web/API/Topics_API) *Experimental* Non-standard
- [ ] [Touch Events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events)
- [ ] [Trusted Types API](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API)

**Comment by taoliujun** [comment]
### U
- [ ] [UI Events](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events)
- [ ] [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL_API)
- [ ] [URL Pattern API](https://developer.mozilla.org/en-US/docs/Web/API/URL_Pattern_API) *Experimental*
- [ ] [User-Agent Client Hints API](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API) *Experimental*

### V
- [ ] [Vibration API](https://developer.mozilla.org/en-US/docs/Web/API/Vibration_API)
- [ ] [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) *Experimental*
- [ ] [VirtualKeyboard API](https://developer.mozilla.org/en-US/docs/Web/API/VirtualKeyboard_API) *Experimental*
- [ ] [Visual Viewport](https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API)

### W
- [ ] [Web Animations](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API)
- [ ] [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API)
- [ ] [Web Authentication API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API)
- [ ] [Web Components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components)
- [ ] [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API)
- [ ] [Web Locks API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API)
- [ ] [Web MIDI API](https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API)
- [ ] [Web NFC API](https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API) *Experimental*
- [ ] [Web Notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API)
- [ ] [Web Serial API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API) *Experimental*
- [ ] [Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API)
- [ ] [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API)
- [ ] [Web Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API)
- [ ] [Web Workers API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API)
- [ ] [WebCodecs API](https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API)
- [ ] [WebGL](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API)
- [ ] [WebGPU API](https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API) *Experimental*
- [ ] [WebHID API](https://developer.mozilla.org/en-US/docs/Web/API/WebHID_API) *Experimental*
- [ ] [WebOTP API](https://developer.mozilla.org/en-US/docs/Web/API/WebOTP_API)
- [ ] [WebRTC](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API)
- [ ] [WebSockets API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API)
- [ ] [WebTransport API](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport_API)
- [ ] [WebUSB API](https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API) *Experimental*
- [ ] [WebVR API](https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API) Non-standard Deprecated
- [ ] [WebVTT](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API)
- [ ] [WebXR Device API](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API) *Experimental*
- [ ] [Window Controls Overlay API](https://developer.mozilla.org/en-US/docs/Web/API/Window_Controls_Overlay_API) *Experimental*
- [ ] [Window Management API](https://developer.mozilla.org/en-US/docs/Web/API/Window_Management_API) *Experimental*

### X
- [ ] [XMLHttpRequest API](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API)

### Y

//

### Z

//
